### ISSUE TITLE
❌ Deployment failed: Error: Unable to make progress anymore among:

### ISSUE THREAD

**Issue by andrelcalves** [aws-solutions-library-samples/guidance-for-carbon-data-lake-on-aws#14]
I encountered issues with CDK version 2.82.0 when trying to deploy the application using cdk deploy --all as mentation in the readme file. However, I used a workaround to successfully deploy the application. The workaround involves deploying the SharedResources stack first, for example with the command cdk deploy SharedResources, and then deploying the LineageStack, and so on in the desired sequence.

Prabably the defect originates in CDK 2.80.0.

**Comment by otoshane** [comment]
Hey Andre,

We’ve had other users experience the same issue with the latest updates to CDK. We are working on understanding the problem and will update the repository with any necessary changes.

Users that have reported this issue have resolved deployment challenges by reverting their CDK CLI back to version 2.79.1.

Please let us know how we can provide further support and guidance. Also, please feel free to reach out to me at otoshane@amazon.com for further questions or concerns.

Thanks and Best,

Shane

**Comment by samwardbiddle** [comment]
Hello @andrelcalves -- I am checking in on this issue, and we are updating the lastest CDK CLI version in `package.json` to `^2.83.1`. Will verify completion when this is ready.

**Comment by samwardbiddle** [comment]
Hey @andrelcalves . Thanks again for bringing this to our attention. We have updated the versions of `aws-cdk` and `aws-cdk-lib` in `package.json` and `package-lock.json` to reflect the latest versions. We have confirmed through test that this will fix the issue you encountered. Please also note that to ensure you are working with the latest version of the AWS CDK CLI you must also install the latest version globally: `npm i -g aws-cdk`
