### ISSUE TITLE
Runtimes specific to a language or framework version are deprecated when the version reaches end of life. 

### ISSUE THREAD

**Issue by mfsuen** [aws-solutions-library-samples/guidance-for-carbon-data-lake-on-aws#40]
After "cdk synth", it shows the following errors, it seems there are Lambda function "nodejs" runtime version is not compatible. 

[Error at /LineageStack/cdlDataLineageInput/Resource] AwsSolutions-L1:
[Error at /LineageStack/cdlDataLineageHandler/Resource] AwsSolutions-L1:
[Error at /LineageStack/cdlDataLineageTraceHandler/Resource] AwsSolutions-L1: 
[Error at /TestStack/CalculatorTestLambda/Resource] AwsSolutions-L1:
[Error at /TestStack/PipelineTestLambda/Resource] AwsSolutions-L1:

<img width="967" alt="cdk-synth-error" src="https://github.com/aws-solutions-library-samples/guidance-for-carbon-data-lake-on-aws/assets/23135257/e96fe966-5189-49b3-9b8b-3b8186d84246">

**Comment by cmgabri** [comment]
Updated Lambda runtime to Python 3.12, updated AWSLambdaPowertoolsPython to fix this issue. Thank you for opening this issue.
